;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Drink",DevComment="")
+GameplayTagList=(Tag="Action.Eat",DevComment="")
+GameplayTagList=(Tag="Action.Hide",DevComment="")
+GameplayTagList=(Tag="Action.Leisure",DevComment="")
+GameplayTagList=(Tag="Action.Sit",DevComment="")
+GameplayTagList=(Tag="Action.Toilet",DevComment="")
+GameplayTagList=(Tag="ChainedBehaviour",DevComment="")
+GameplayTagList=(Tag="Interruption",DevComment="")

